### ISSUE TITLE
Determine if plugin should use 'implementation' or 'api' dependencies instead of 'compile' dependencies

### ISSUE THREAD

**Issue by Sporking** [openjfx/javafx-gradle-plugin#13]
The code in the JavaFXPlugiln.applyDepencencies function appears to be creating "compile" dependencies, but current Gradle advice is to consider these deprecated.

More information here:

https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

**Comment by tiainen** [comment]
It's true that we should not add the dependencies to the deprecated `compile` configuration.

As it stands now, it doesn't make much sense to expose the JavaFX dependencies because of the platform dependent way the maven artifacts are built up. For that reason, `implementation` makes most sense, for both cases where either the `java` or the `java-library` plugin is applied.
