### ISSUE TITLE
How to support both Java 11 and older versions in one Gradle project?

### ISSUE THREAD

**Issue by dgelessus** [openjfx/javafx-gradle-plugin#4]
Can this plugin be used in a project that wants to support Java 11 with OpenJFX, but also remain compatible with older Java versions (mainly Java 8) that come with JavaFX included?

At the moment the plugin is built for Java 11 and can't be loaded at all on older Java versions (#2). Would it be possible to build the plugin with support for Java 8, and simply do nothing on Java versions before 11 (since JavaFX is already included in that case)?

I can of course manually check `JavaVersion.current().java11Compatible` and not load the plugin on older Java versions, but it's not a great solution: I have to add manual `if`s in multiple places, and it only works with the old `buildscript` syntax (since `if`s are not allowed in the new `plugins` block).

**Comment by tiainen** [comment]
This plugin is only useful for projects that want to use JavaFX 11+. As you already pointed out, it's easy to check the java version in the build script.

You can still use `plugins` and combine it with `apply false`:

    id 'org.openjfx.javafxplugin' version '0.0.5' apply false

You can then apply the plugin later on at any time you need it with:

    apply plugin: 'org.openjfx.javafxplugin'

**Comment by dgelessus** [comment]
Ah, I forgot about `apply false`, thanks for the tip.

Would it make sense to add an example of this to the README? (I can make a PR if you like.)

**Comment by altavir** [comment]
Still, it would vote for a check inside the plugin so it could be used safely for migrating projects.

**Comment by tiainen** [comment]
This would require the code and produced artifacts to be compatible with Java 8. This is currently not possible because this plugin makes use of the [gradle modules plugin](https://github.com/java9-modularity/gradle-modules-plugin), which is also only runnable in a Java 11 environment.

For projects that are in a migration phase, there is an easy workaround by [lazily applying the plugin as mentioned above](https://github.com/openjfx/javafx-gradle-plugin/issues/4#issuecomment-442499405).
